version: '3.9'

services:
  backend:
    image: <IMAGE_NAME>
    restart: always
    ports:
      - 80:3000
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
