version: '3.9'

services:
  backend_dev:
    image: <IMAGE_NAME>
    restart: always
    ports:
      - 81:3000
    env_file:
      - .env.dev
    networks:
      - backend

networks:
  backend:
    driver: bridge
