---
- name: Update apt cache
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

- name: Create App Directory
  hosts: all
  remote_user: ubuntu

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /home/ubuntu/app
        state: directory
        mode: '0755'

- name: Install Docker and Docker Compose
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: true

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

- name: Fazendo login na dockerhub
  hosts: all
  remote_user: ubuntu
  become: true

  vars:
    username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKERHUB_TOKEN') }}"

  tasks:
    - name: Log in DockerHub
      community.docker.docker_login:
        username: '{{ username }}'
        password: '{{ password }}'

- name: Download container image
  hosts: all
  remote_user: ubuntu
  become: true

  vars:
    image_name: "{{ lookup('env', 'IMAGE_NAME') }}"

  tasks:
    - name: Pull the image
      community.docker.docker_image:
        name: '{{ image_name }}'
        source: pull

- name: Config .env file
  hosts: all
  remote_user: ubuntu
  become: true

  vars:
    node_env: "{{ lookup('env', 'NODE_ENV') }}"

  tasks:
    - name: Create a .env file
      copy:
        dest: '/home/ubuntu/app/.env'
        content: |
          NODE_ENV = {{ node_env }}

- name: Copy docker-compose.yml file
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: coping
      ansible.builtin.copy:
        src: ./../docker-compose.yml
        dest: /home/ubuntu/app/docker-compose.yml

- name: Update docker-compose.yml image name in file
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update image name in docker-compose.yml
      replace:
        path: /home/ubuntu/app/docker-compose.yml
        regexp: '<IMAGE_NAME>'
        replace: "{{ lookup('env', 'IMAGE_NAME') }}"

- name: Execute docker-compose
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Execute docker-compose
      shell: docker-compose -f /home/ubuntu/app/docker-compose.yml up -d
