name: Config VM using Ansible

on:
  workflow_dispatch:
    inputs:
      instance_public_ip:
        required: true
        description: 'Instance Public IP'
        default: ''
      environment:
        required: true
        type: choice
        description: 'Environment'
        options:
          - development
          - production
      image_name:
        required: true
        description: 'Docker Image Name'
        default: ''

jobs:
  config_vm_with_ansible:
    runs-on: ubuntu-latest

    env:
      PUBLIC_IP: ${{ inputs.instance_public_ip }}
      ANSIBLE_HOST_KEY_CHECKING: false
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME: ${{ inputs.image_name }}
      NODE_ENV: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Create SSH Authorized Key File
        run: |
          echo "${{ secrets.COMPUTE_SSH_AUTHORIZED_PRIVATE_KEY }}" > compute_ssh_authorized_private_key.pem
          chmod 600 compute_ssh_authorized_private_key.pem

      - name: Run Prod Ansible Playbook
        if: ${{ inputs.environment == 'production' }}
        run: ansible-playbook -i $PUBLIC_IP, --user ubuntu --private-key compute_ssh_authorized_private_key.pem ./ansible/playbook.yml

      - name: Run Dev Ansible Playbook
        if: ${{ inputs.environment == 'development' }}
        run: ansible-playbook -i $PUBLIC_IP, --user ubuntu --private-key compute_ssh_authorized_private_key.pem ./ansible/playbook-dev.yml
